### ISSUE TITLE
内存暴涨问题

### ISSUE THREAD

**Issue by shaofengzeng** [HeatherJiaZG/SuperGlue-pytorch#2]
您好，打扰了，再测试代码过程中，发现内存暴涨，几乎占满整个内存(测试机器256G内存)，运行速度因此变得非常慢...
代码在初次运行中报错:
Traceback (most recent call last):
  File "/home/xp1/workdir/SuperGlue-pytorch/train.py", line 183, in <module>
    data = superglue(pred)
  File "/home/xp1/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xp1/workdir/SuperGlue-pytorch/models/superglue.py", line 259, in forward
    desc0 = desc0 + self.kenc(kpts0, torch.transpose(data['scores0'], 0, 1))
  File "/home/xp1/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xp1/workdir/SuperGlue-pytorch/models/superglue.py", line 84, in forward
    return self.encoder(torch.cat(inputs, dim=1))
RuntimeError: Expected object of scalar type Double but got scalar type Float for sequence element 1 in sequence argument at position #1 'tensors'
定位到出错位置为：KeypointEncoder类下的forward函数
后修改
inputs = [kpts.transpose(1, 2), scores.unsqueeze(1)]
为
inputs = [kpts.transpose(1, 2).double(), scores.unsqueeze(1).double()]
程序可运行，但1次epoch刚运行约一半，就出现内存暴涨问题
希望您能抽时间帮我解答，如果方便您也可以加我的QQ：905181289
非常期待能和您交流，谢谢。

**Comment by HeatherJiaZG** [comment]
Hello，感谢您的反馈！可以试一下最新的train.py，主要改了epoch_loss += Loss.item()，加过您qq啦
