### ISSUE TITLE
ValueError: Expected more than 1 spatial element when training, got input size torch.Size([1, 32, 1])

### ISSUE THREAD

**Issue by cuiyun-fang** [HeatherJiaZG/SuperGlue-pytorch#31]
@HeatherJiaZG  您好！感谢您提供的代码！但是我在运行`python train.py`时出现了以下报错：
`Traceback (most recent call last):
  File "/home/jhk/work code/SuperGlue-pytorch-master/train.py", line 172, in <module>
    data = superglue(pred)
  File "/home/jhk/anaconda3/envs/openglue/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jhk/work code/SuperGlue-pytorch-master/models/superglue.py", line 262, in forward
    desc1 = desc1 + self.kenc(kpts1, torch.transpose(data['scores1'], 0, 1))
  File "/home/jhk/anaconda3/envs/openglue/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jhk/work code/SuperGlue-pytorch-master/models/superglue.py", line 83, in forward
    return self.encoder(torch.cat(inputs, dim=1))
  File "/home/jhk/anaconda3/envs/openglue/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jhk/anaconda3/envs/openglue/lib/python3.8/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/home/jhk/anaconda3/envs/openglue/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jhk/anaconda3/envs/openglue/lib/python3.8/site-packages/torch/nn/modules/instancenorm.py", line 72, in forward
    return self._apply_instance_norm(input)
  File "/home/jhk/anaconda3/envs/openglue/lib/python3.8/site-packages/torch/nn/modules/instancenorm.py", line 32, in _apply_instance_norm
    return F.instance_norm(
  File "/home/jhk/anaconda3/envs/openglue/lib/python3.8/site-packages/torch/nn/functional.py", line 2482, in instance_norm
    _verify_spatial_size(input.size())
  File "/home/jhk/anaconda3/envs/openglue/lib/python3.8/site-packages/torch/nn/functional.py", line 2449, in _verify_spatial_size
    raise ValueError("Expected more than 1 spatial element when training, got input size {}".format(size))
ValueError: Expected more than 1 spatial element when training, got input size torch.Size([1, 32, 1])`
请问您事先对数据集是否进行过其他处理，或者您是否知道这个报错如何能解决？万分感谢！

**Comment by lihaoling** [comment]
I also encountered the same problem, please tell me if you solved it

**Comment by lihaoling** [comment]
I also encountered the same problem, please tell me if you solved it

**Comment by xiao-longlong** [comment]
我也遇到了类似的问题，如下
File "/workspace/train.py", line 172, in <module>
    data = superglue(pred)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/models/superglue.py", line 260, in forward
    desc1 = desc1 + self.kenc(kpts1, torch.transpose(data['scores1'], 0, 1))
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/models/superglue.py", line 83, in forward
    return self.encoder(torch.cat(inputs, dim=1))
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/container.py", line 204, in forward
    input = module(input)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/instancenorm.py", line 74, in forward
    return self._apply_instance_norm(input)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/instancenorm.py", line 34, in _apply_instance_norm
    return F.instance_norm(
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/functional.py", line 2494, in instance_norm
    _verify_spatial_size(input.size())
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/functional.py", line 2461, in _verify_spatial_size
    raise ValueError("Expected more than 1 spatial element when training, got input size {}".format(size))
ValueError: Expected more than 1 spatial element when training, got input size torch.Size([1, 32, 1])
而且此问题发生在第一个epoch的中间，并不是一开始就出现维度错误。

**Comment by pureloveljc** [comment]
load_data

if len(kp1) <= 1 or len(kp2) <= 1:

**Comment by ttaohe** [comment]
> encoder

请问这个是添加到哪里呢？

**Comment by Syfback** [comment]
raceback (most recent call last):
  File "Y:\torch_xiangmu\SuperGlue-pytorch-master\train.py", line 172, in <module>
    data = superglue(pred)
  File "Y:\Anaconda3\envs\syf\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "Y:\torch_xiangmu\SuperGlue-pytorch-master\models\superglue.py", line 257, in forward
    desc1 = desc1 + self.kenc(kpts1, torch.transpose(data['scores1'], 0, 1))
  File "Y:\Anaconda3\envs\syf\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "Y:\torch_xiangmu\SuperGlue-pytorch-master\models\superglue.py", line 83, in forward
    return self.encoder(torch.cat(inputs, dim=1))
  File "Y:\Anaconda3\envs\syf\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "Y:\Anaconda3\envs\syf\lib\site-packages\torch\nn\modules\container.py", line 217, in forward
    input = module(input)
  File "Y:\Anaconda3\envs\syf\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "Y:\Anaconda3\envs\syf\lib\site-packages\torch\nn\modules\instancenorm.py", line 74, in forward
    return self._apply_instance_norm(input)
  File "Y:\Anaconda3\envs\syf\lib\site-packages\torch\nn\modules\instancenorm.py", line 34, in _apply_instance_norm
    return F.instance_norm(
  File "Y:\Anaconda3\envs\syf\lib\site-packages\torch\nn\functional.py", line 2494, in instance_norm
    _verify_spatial_size(input.size())
  File "Y:\Anaconda3\envs\syf\lib\site-packages\torch\nn\functional.py", line 2461, in _verify_spatial_size
    raise ValueError("Expected more than 1 spatial element when training, got input size {}".format(size))
ValueError: Expected more than 1 spatial element when training, got input size torch.Size([1, 32, 1])
我也有这样的问题，请问怎么解决呢？
