### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by Shuhul24** [HeatherJiaZG/SuperGlue-pytorch#32]
I am training the model on my dataset instead of what is mentioned on the github repository (COCO, etc.). While training following error occured:
```python
Traceback (most recent call last):
  File "/home/shuhulh/superglue_train/train.py", line 164, in <module>
    for i, pred in enumerate(train_loader):
  File "/opt/conda/envs/animal-reid/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/opt/conda/envs/animal-reid/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 671, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/opt/conda/envs/animal-reid/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/envs/animal-reid/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/shuhulh/superglue_train/load_data.py", line 30, in __getitem__
    width, height = image.shape[:2]
AttributeError: 'NoneType' object has no attribute 'shape'
```
I don't understand why does it happen while training. Can you help me out what am I supposed to do here? Do I need to change the name of files (the images) in the image directory (they are usually numerical values).

**Comment by w1168** [comment]
same error

**Comment by chefewq** [comment]
the error caused maybe by wrong  image_path
